### ISSUE TITLE
Keeps on crashing under load

### ISSUE THREAD

**Issue by BenBE** [rakshasa/rtorrent#1047]
While downloading a single torrent (multifile, ~1TiB, 16MiB chunks) I keep on seeing crashes of rtorrent that result in the following backtrace:

```
Caught internal_error: DhtServer::event_write called but both write queues are empty.
/usr/lib/x86_64-linux-gnu/libtorrent.so.21(_ZN7torrent14internal_error10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x257) [0x7fc9c517f4e7]
/usr/lib/x86_64-linux-gnu/libtorrent.so.21(_ZN7torrent14internal_errorC1EPKc+0x98) [0x7fc9c517b1d8]
/usr/lib/x86_64-linux-gnu/libtorrent.so.21(+0x3484c) [0x7fc9c516d84c]
/usr/lib/x86_64-linux-gnu/libtorrent.so.21(_ZN7torrent9PollEPoll7performEv+0xed) [0x7fc9c5199e6d]
/usr/lib/x86_64-linux-gnu/libtorrent.so.21(_ZN7torrent9PollEPoll7do_pollEli+0x69) [0x7fc9c5199f59]
/usr/lib/x86_64-linux-gnu/libtorrent.so.21(_ZN7torrent11thread_base10event_loopEPS0_+0x12b) [0x7fc9c51cff6b]
rtorrent(+0x4459e) [0x5585c07bd59e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fc9c4d240b3]
rtorrent(+0x44ebe) [0x5585c07bdebe]
```

Using: rTorrent 0.9.8/libtorrent 0.13.8 on Ubuntu 20.04.

**Comment by SkyREgit** [comment]
OS: FreeBSD 13.1-RELEASE-p9
rtorrent: 0.9.8, 0.10.0
libtorrent: 0.13.8, 0.14.0

Issue still persists.
Should rtorrent throw exception and shutdown in such case?

**Comment by stickz** [comment]
@SkyREgit Please wait for the next release to be tagged. A lot of these issues are resolved upstream.

**Comment by rakshasa** [comment]
Old version, try new release.

**Comment by SkyREgit** [comment]
OS: FreeBSD 13.3-RELEASE
rtorrent: 0.15.1
libtorrent: 0.15.1

Issue still persists.
Should rtorrent throw exception and shutdown in such case?

**Comment by SkyREgit** [comment]
```
# cat rtorrent-1741960318.log rtorrent-1741961698.log rtorrent-1742139958.log
1741960318 N rtorrent main: Starting thread.
1741960318 N rtorrent scgi: Starting thread.
1741960495 N rtorrent scgi: Shutting down thread.
1741960544 C Caught internal_error: 'DhtServer::event_write called but both write queues are empty.'.
---DUMP---
0x823caa2a2 <_ZN7torrent14internal_error10initializeERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE+0x42> at /usr/local/lib/libtorrent.so.23
0x29226a <_ZN7torrent14internal_errorC2EPKc+0xca> at /usr/local/bin/rtorrent
0x823ccfa38 <_ZN7torrent11TrackerList21receive_scrape_failedEPNS_7TrackerERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE+0x16808> at /usr/local/lib/libtorrent.so.23
0x823cb198e <_ZN7torrent10PollKQueue7performEv+0x12e> at /usr/local/lib/libtorrent.so.23
0x823cb1af8 <_ZN7torrent10PollKQueue7do_pollEli+0xf8> at /usr/local/lib/libtorrent.so.23
0x823ca4b86 <_ZN7torrent11thread_base10event_loopEPS0_+0x186> at /usr/local/lib/libtorrent.so.23

---END---
1741961698 N rtorrent main: Starting thread.
1741961698 N rtorrent scgi: Starting thread.
1742003093 C Caught internal_error: 'DhtServer::event_write called but both write queues are empty.'.
---DUMP---
0x82466b2a2 <_ZN7torrent14internal_error10initializeERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE+0x42> at /usr/local/lib/libtorrent.so.23
0x29226a <_ZN7torrent14internal_errorC2EPKc+0xca> at /usr/local/bin/rtorrent
0x824690a38 <_ZN7torrent11TrackerList21receive_scrape_failedEPNS_7TrackerERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE+0x16808> at /usr/local/lib/libtorrent.so.23
0x82467298e <_ZN7torrent10PollKQueue7performEv+0x12e> at /usr/local/lib/libtorrent.so.23
0x824672af8 <_ZN7torrent10PollKQueue7do_pollEli+0xf8> at /usr/local/lib/libtorrent.so.23
0x824665b86 <_ZN7torrent11thread_base10event_loopEPS0_+0x186> at /usr/local/lib/libtorrent.so.23

---END---
1742139958 N rtorrent main: Starting thread.
1742139958 N rtorrent scgi: Starting thread.
1742141229 C Caught internal_error: 'DhtServer::event_write called but both write queues are empty.'.
---DUMP---
0x8235092a2 <_ZN7torrent14internal_error10initializeERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE+0x42> at /usr/local/lib/libtorrent.so.23
0x29226a <_ZN7torrent14internal_errorC2EPKc+0xca> at /usr/local/bin/rtorrent
0x82352ea38 <_ZN7torrent11TrackerList21receive_scrape_failedEPNS_7TrackerERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE+0x16808> at /usr/local/lib/libtorrent.so.23
0x82351098e <_ZN7torrent10PollKQueue7performEv+0x12e> at /usr/local/lib/libtorrent.so.23
0x823510af8 <_ZN7torrent10PollKQueue7do_pollEli+0xf8> at /usr/local/lib/libtorrent.so.23
0x823503b86 <_ZN7torrent11thread_base10event_loopEPS0_+0x186> at /usr/local/lib/libtorrent.so.23

---END---
```
