### ISSUE TITLE
Server costs not being covered due to lack of donations.

### ISSUE THREAD

**Issue by rakshasa** [rakshasa/rtorrent#1101]
Due to this #1099 issue I looked closer at the current expenses and atm it costs me $30-50 a month to run this server.

I wouldn’t mind, except pretty much no one donates to this project, having only a single donation once in the past couple months and a few bucks through patreon.

If there’s not enough to cover even the server cost I’ll be shutting it down and/or remove the downloads directory.

**Comment by Micdu70** [comment]
Hello, I would like to donate via Paypal but Paypal is telling "This beneficiary cannot accept payments at this time.". 😢

**Comment by rakshasa** [comment]
Is that the old address? The current one should have an ‘+jp’ before the ‘@‘.

**Comment by rakshasa** [comment]
Last one was ten days ago, so should work with the new one.

**Comment by Micdu70** [comment]
Oh, yes, you should remove the donate button from the README.md. ^^

**Comment by rakshasa** [comment]
Fixed button, missed that one.

**Comment by Micdu70** [comment]
Donation sent (with love ^^). 👍

**Comment by Micdu70** [comment]
Oh, one thing to report, it seems you forgot to renew the SSL certificate for "rtorrent.net" (or just forgot to reload the configuration of the web server). ^^

**Comment by rakshasa** [comment]
As you might have noticed I’m not exactly infra admin material. I’ll look into it.

**Comment by rakshasa** [comment]
I've changed the links to use e.g. `https://github.com/rakshasa/rtorrent-archive/raw/master/libtorrent-0.13.8.tar.gz` for old releases.

Anyone managing anything that downloads rtorrent packages should redirect to the archive repo as it doesn't seem like I'm getting enough donations for it to be worth running.

From future releases onwards I'll be making special `package-vX.X.X` tags that contain only the files from the generated packages. So from 0.9.9 onwards the urls will be different from the above.

**Comment by callowaylc** [comment]
> Anyone managing anything that downloads rtorrent packages should redirect to the archive repo

You can deploy versioned  artifacts,  as a "release", to your working repository, as in the [following example](https://github.com/callowaylc/logger/releases). It's easy to automate and I am sure some free whatever-as-a-service exists, though its really just a little shell and [gh release](https://cli.github.com/manual/gh_release_create). Committing binaries to version control is just the [worst kind of fingernails on the chalkboard](https://github.com/rakshasa/rtorrent-archive/commit/4186ad69d321fbc75c7144a53987253f7aed18cb#diff-e70abc89fd99923d0ed5f7be556af57a8cde9c4d7887016089b4b2e716f6b108).

>As you might have noticed I’m not exactly infra admin material. I’ll look into it.

https://letsencrypt.org/

I've never been to rtorrent.net and don't know what it's raison d'etre is, but if it was to just serve downloads, then I wouldnt bother keeping it up, even if I were the wealthiest man in Queens. If you're hosting with any of the IAAS providers, like AWS, GCP, etc, they charge on bandwidth usage, especially any requests that move data out of their DC (like downloads). In effect, the more popular your tool becomes, the more cost falls on your shoulders, which is a ridiculous waste of money.  There are a million free way to host artifacts, like github releases, that are minimalist and part of the community zeitgeist.

**Comment by csgithubgamer** [comment]
sudo apt-get install rtorrent

I can't install rtorrent client on Debian 7, because is no access to this file:
"Failed to get http://ftp.fr.debian.org/debian/pool/main/x/xmlrpc-c/libxmlrpc-core-c3_1.16.33-3.2_amd64.deb 404 Not Found"

**How to solve this issue?**

**Comment by rakshasa** [comment]
Downstream packaging issues should be reported to the distro, not here.
