### ISSUE TITLE
Not sent the stopped request to tracker after remove seeded torrent

### ISSUE THREAD

**Issue by yandrey0** [rakshasa/rtorrent#1477]
0.15.3 --with-xmlrpc-tinyxml2 via command `d.erase`

**Comment by Sappurit** [comment]
This bug since 0.9.6, and also not reported when completed download. 
We have to wait until the timer countdown 1800 to 0.
We have to modify src/tracker/tracker_controller.cc
and also break a loop when success reported to one of the trackers.

```
if (!(m_flags & flag_active) || !m_tracker_list->has_usable()) {
    LT_LOG_TRACKER_EVENTS("sending completed event : queued", 0);

    // Fix hashing and waiting for the next timeout 
    // Sappurit

    for (auto tracker : *m_tracker_list) {
      if (!tracker.is_usable())
        continue;

      m_tracker_list->send_event(tracker, tracker::TrackerState::EVENT_NONE);
      break;
    }

    return;
  }
```

and

```
  for (auto tracker : *m_tracker_list) {
    if (!tracker.is_in_use())
      continue;

    m_tracker_list->send_event(tracker, tracker::TrackerState::EVENT_COMPLETED);
    break; // Sappurit
  }

```

**Comment by rakshasa** [comment]
I'll look into this at some point.

**Comment by rakshasa** [comment]
Note to self; add a std::weak_ptr to the callback and use that to disable STOPPED http request callbacks rather than canceling them.

**Comment by rakshasa** [comment]
This should now be fixed.

**Comment by rakshasa** [comment]
Considering this as fixed.

**Comment by yandrey0** [comment]
0.16.12 - not fixed, announce interval is broken, requests sent every few second.

**Comment by rakshasa** [comment]
You need to be more specific about the behavior that is broken.

Trackers now live after the download is erased, and as such should be finishing STOPPED announce requests.

**Comment by yandrey0** [comment]
add/del test torrent:
```
1779264681 I resource_manager: balancing upload unchoked slots; current_unchoked:0 change:0 max_unchoked:20
1779264681 I resource_manager: balancing download unchoked slots; current_unchoked:0 change:0 max_unchoked:100
1779264699 tracker::manager: added controller: info_hash:5AAD957023887B1EF3C0E2300D1DA82132574267
1779264699 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: added tracker : requester:0x55dcb35683f0 group:0 url:http://bt.test/announce.php
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->resource_manager: set priority: 0
1779264699 I resource_manager: adjusting upload unchoked slots; current:0 adjusted:0
1779264699 I resource_manager: adjusting upload unchoked slots; current:0 adjusted:0
1779264699 I resource_manager: adjusting download unchoked slots; current:0 adjusted:0
1779264699 I resource_manager: adjusting download unchoked slots; current:0 adjusted:0
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Closing download directly.
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Inserting download.
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Closing download directly.
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Resuming download: flags:0.
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Opening download.
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download: Opening torrent: flags:1.
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download: Checking hash: allocated:1 try_quick:1.
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download: update priorities: chunks_selected:986 wanted_chunks:0
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Hash done.
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Resuming download: flags:0.
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->resource_manager: set priority: 0
1779264699 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download: Starting torrent: flags:0.
1779264699 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_controller: enabled : trackers:1
1779264699 5AAD957023887B1EF3C0E2300D1DA82132574267->download: Setting new baseline on start: uploaded:0 completed:64561967.
1779264699 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_controller: sending start event : requesting
1779264699 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: sending started : requester:0x55dcb35683f0 url:http://bt.test/announce.php
1779264699 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : sending event : state:started family:AF_INET url:http://bt.test/announce.php
1779264700 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : received reply : state:started url:http://bt.test/announce.php
1779264700 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : tracker reply : state:started url:http://bt.test/announce.php : interval:3600 min_interval:3600 complete:0 incomplete:0 downloaded:0
1779264700 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : sending event : state:started family:AF_INET6 url:http://bt.test/announce.php
1779264700 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: received 0 new peers : requester:0x55dcb35683f0 group:0 url:http://bt.test/announce.php
1779264700 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : received failure : previous family succeeded : url:http://bt.test/announce.php : Bind address for requested IP protocol(s) not available.
1779264700 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: received 0 peers : requester:0x55dcb35683f0 group:0 url:http://bt.test/announce.php
1779264711 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_controller: started requesting
1779264711 tracker_next_timeout_promiscuous: min_interval:300 use_interval:0 since_last:11
1779264711 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: sending updated : requester:0x55dcb35683f0 url:http://bt.test/announce.php
1779264711 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : sending event : state:updated family:AF_INET url:http://bt.test/announce.php
1779264712 I resource_manager: balancing upload unchoked slots; current_unchoked:0 change:0 max_unchoked:20
1779264712 I resource_manager: balancing download unchoked slots; current_unchoked:0 change:0 max_unchoked:100
1779264712 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : received reply : state:updated url:http://bt.test/announce.php
1779264712 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : tracker reply : state:updated url:http://bt.test/announce.php : interval:3600 min_interval:3600 complete:0 incomplete:0 downloaded:0
1779264712 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : sending event : state:updated family:AF_INET6 url:http://bt.test/announce.php
1779264712 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: received 0 new peers : requester:0x55dcb35683f0 group:0 url:http://bt.test/announce.php
1779264712 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : received failure : previous family succeeded : url:http://bt.test/announce.php : Bind address for requested IP protocol(s) not available.
1779264712 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: received 0 peers : requester:0x55dcb35683f0 group:0 url:http://bt.test/announce.php
1779264743 I resource_manager: balancing upload unchoked slots; current_unchoked:0 change:0 max_unchoked:20
1779264743 I resource_manager: balancing download unchoked slots; current_unchoked:0 change:0 max_unchoked:100
1779264743 tracker_next_timeout_promiscuous: min_interval:300 use_interval:0 since_last:31
1779264743 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: sending updated : requester:0x55dcb35683f0 url:http://bt.test/announce.php
1779264743 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : sending event : state:updated family:AF_INET url:http://bt.test/announce.php
1779264744 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : received reply : state:updated url:http://bt.test/announce.php
1779264744 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : tracker reply : state:updated url:http://bt.test/announce.php : interval:3600 min_interval:3600 complete:0 incomplete:0 downloaded:0
1779264744 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : sending event : state:updated family:AF_INET6 url:http://bt.test/announce.php
1779264744 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: received 0 new peers : requester:0x55dcb35683f0 group:0 url:http://bt.test/announce.php
1779264744 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : received failure : previous family succeeded : url:http://bt.test/announce.php : Bind address for requested IP protocol(s) not available.
1779264744 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: received 0 peers : requester:0x55dcb35683f0 group:0 url:http://bt.test/announce.php
1779264751 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Erasing download.
1779264751 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Closing download with throw.
1779264751 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Pausing download: flags:0.
1779264751 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download: Stopping torrent: flags:0.
1779264751 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_controller: sending stop event : requesting
1779264751 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_list: sending stopped : requester:0x55dcb35683f0 url:http://bt.test/announce.php
1779264751 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_controller: disabled : trackers:1
1779264751 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download: Closing torrent: flags:0.
1779264751 I 5AAD957023887B1EF3C0E2300D1DA82132574267->download_list: Pausing download: flags:0.
1779264751 tracker::manager: removed controller: info_hash:5AAD957023887B1EF3C0E2300D1DA82132574267
1779264751 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : sending event : state:stopped family:AF_INET url:http://bt.test/announce.php
1779264751 5AAD957023887B1EF3C0E2300D1DA82132574267->tracker_http: 0x55dcb35683f0 : cleaning up : state:stopped url:http://bt.test/announce.php
1779264773 I resource_manager: balancing upload unchoked slots; current_unchoked:0 change:0 max_unchoked:20
1779264773 I resource_manager: balancing download unchoked slots; current_unchoked:0 change:0 max_unchoked:100
1779264804 I resource_manager: balancing upload unchoked slots; current_unchoked:0 change:0 max_unchoked:20
1779264804 I resource_manager: balancing download unchoked slots; current_unchoked:0 change:0 max_unchoked:100
1779264835 I resource_manager: balancing upload unchoked slots; current_unchoked:0 change:0 max_unchoked:20
1779264835 I resource_manager: balancing download unchoked slots; current_unchoked:0 change:0 max_unchoked:100
1779264862 udp_router: closed udp router
```

**Comment by rakshasa** [comment]
Looks like there's a thread timing issue.

The tracker isn't marked as requesting until it the callback is executed in tracker_thread, while it is being added to the deletion queue in main thread.

**Comment by rakshasa** [comment]
Merged fix.
