### ISSUE TITLE
rtorrent 0.15.3 GUI locks when running a execute command that runs rtcontrol

### ISSUE THREAD

**Issue by laplacesdaemon** [rakshasa/rtorrent#1486]
With rtorrent 0.15.3 and pyrosimple 2.14.2 running a execute command that calls rtcontrol locks the rtorrent GUI. Killing the launched rtcontrol process revives the GUI. This worked with rtorrent 0.15.1

Running rtcontrol from a bash shell works, both when generationg stdout output and outputing to the rtcontrol view.

**Comment by rakshasa** [comment]
Post the specific command.

Also include execute log with `log.execute = /foo/logs/execute.log`.

**Comment by laplacesdaemon** [comment]
Some example commands:

```
method.insert = t, simple|private, "execute.nothrow=/home/rtorrent/.local/bin/rtcontrol, --detach, -qV, \"$cat=\\\"alias=\\\",$argument.0=\""
method.insert = tag.add, simple|private, "execute.nothrow={/home/rtorrent/.local/bin/rtcontrol,--detach,--yes,(cat,hash=,$d.hash=),--tag,$argument.0=} ; tag.show="
method.insert = fm,   private|simple, "execute=/home/rtorrent/.local/bin/rtcontrol, -qV, custom_1=Movies,   -s, completed, -r"

Running any of those three commands
t=/tracker/
tag.add=aTag
fm=
```

locs the GUI and I have to kill rtcontrol to unlock it.

execute.log doesn't show much:
```
---
/home/rtorrent/.local/bin/rtcontrol --detach -qV alias=/trackerName/
---
Terminating on signal 15

--- Error ---

---
/home/rtorrent/.local/bin/rtcontrol --detach --yes hash=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA --tag del
---
Terminating on signal 15

--- Error ---

---
/home/rtorrent/.local/bin/rtcontrol --detach hash=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -o tagged
---
Terminating on signal 15
Captured output:

--- Error ---

---
/home/rtorrent/.local/bin/rtcontrol -qV custom_1=Movies -s completed -r
---

--- Error ---
```

**Comment by rakshasa** [comment]
```
diff --git a/src/rpc/exec_file.cc b/src/rpc/exec_file.cc
index 3be7bfa..2494c8e 100644
--- a/src/rpc/exec_file.cc
+++ b/src/rpc/exec_file.cc
@@ -18,7 +18,7 @@ namespace rpc {
 
 int
 ExecFile::execute(const char* file, char* const* argv, int flags) {
-  // Write the execued command and its parameters to the log fd.
+  // Write the executed command and its parameters to the log fd.
   [[maybe_unused]] int result;
 
   if (m_log_fd != -1) {
@@ -121,7 +121,7 @@ ExecFile::execute(const char* file, char* const* argv, int flags) {
 
   do {
     wpid = waitpid(childPid, &status, 0);
-  } while (wpid == -1 && WIFEXITED(status) == 0);
+  } while (wpid == -1 && errno == EINTR);
 
   if (wpid != childPid)
     throw torrent::internal_error("ExecFile::execute(...) waitpid failed.");
```

Could you try this patch?

**Comment by rakshasa** [comment]
Should be fixed in master.

**Comment by laplacesdaemon** [comment]
Still not working with rtorrent at 231606afc16eef08ec1a344a7aaef7504343bb71 and libtorrent at a0a364e2863356f51d41a27ce7620471666c5c56

**Comment by rakshasa** [comment]
What happens when you try to run the commands in a terminal? Do they successfully exit immediately?

**Comment by laplacesdaemon** [comment]
> What happens when you try to run the commands in a terminal? Do they successfully exit immediately?

Yes.

**Comment by rakshasa** [comment]
When it hangs, use `lldb -p <pid>` or gdb, and show the output of `bt all`.

**Comment by laplacesdaemon** [comment]
```
(lldb) process attach --pid 367849
Process 367849 stopped
* thread #1, name = 'rtorrent main', stop reason = signal SIGSTOP
    frame #0: 0x00007f7f508ade22 libc.so.6`__syscall_cancel_arch at syscall_cancel.S:56
  thread #2, name = 'rtorrent disk', stop reason = signal SIGSTOP
    frame #0: 0x00007f7f508ade22 libc.so.6`__syscall_cancel_arch at syscall_cancel.S:56
  thread #3, name = 'rtorrent net', stop reason = signal SIGSTOP
    frame #0: 0x00007f7f508ade22 libc.so.6`__syscall_cancel_arch at syscall_cancel.S:56
  thread #4, name = 'rtorrent main', stop reason = signal SIGSTOP
    frame #0: 0x00007f7f508ade22 libc.so.6`__syscall_cancel_arch at syscall_cancel.S:56
  thread #5, name = 'rtorrent scgi', stop reason = signal SIGSTOP
    frame #0: 0x00007f7f508ade22 libc.so.6`__syscall_cancel_arch at syscall_cancel.S:56
Executable module set to "/usr/bin/rtorrent".
Architecture set to: x86_64-pc-linux-gnu.
(lldb) bt all
* thread #1, name = 'rtorrent main', stop reason = signal SIGSTOP
  * frame #0: 0x00007f7f508ade22 libc.so.6`__syscall_cancel_arch at syscall_cancel.S:56
    frame #1: 0x00007f7f508a1fda libc.so.6`__internal_syscall_cancel(a1=<unavailable>, a2=<unavailable>, a3=<unavailable>, a4=<unavailable>, a5=0, a6=0, nr=61) at cancellation.c:49:12
    frame #2: 0x00007f7f508a2024 libc.so.6`__syscall_cancel(a1=<unavailable>, a2=<unavailable>, a3=<unavailable>, a4=<unavailable>, a5=0, a6=0, nr=61) at cancellation.c:75:11
    frame #3: 0x00007f7f5091292f libc.so.6`__GI___wait4(pid=<unavailable>, stat_loc=<unavailable>, options=<unavailable>, usage=<unavailable>) at wait4.c:30:10
    frame #4: 0x000055cb3bf11ca2 rtorrent`___lldb_unnamed_symbol2878 + 594
    frame #5: 0x000055cb3bec86a5 rtorrent`___lldb_unnamed_symbol2144 + 69
    frame #6: 0x000055cb3bf0c4e2 rtorrent`___lldb_unnamed_symbol2833 + 98
    frame #7: 0x000055cb3beac64d rtorrent`___lldb_unnamed_symbol1814 + 125
    frame #8: 0x000055cb3bebc5f5 rtorrent`___lldb_unnamed_symbol1964 + 1205
    frame #9: 0x000055cb3bebca9b rtorrent`___lldb_unnamed_symbol1966 + 171
    frame #10: 0x000055cb3bebce5d rtorrent`___lldb_unnamed_symbol1967 + 541
    frame #11: 0x000055cb3bebd04c rtorrent`___lldb_unnamed_symbol1968 + 140
    frame #12: 0x000055cb3bf3f611 rtorrent`___lldb_unnamed_symbol3298 + 129
    frame #13: 0x000055cb3bf3a4bc rtorrent`___lldb_unnamed_symbol3205 + 92
    frame #14: 0x000055cb3bf0c4e2 rtorrent`___lldb_unnamed_symbol2833 + 98
    frame #15: 0x000055cb3beac64d rtorrent`___lldb_unnamed_symbol1814 + 125
    frame #16: 0x000055cb3bebc5f5 rtorrent`___lldb_unnamed_symbol1964 + 1205
    frame #17: 0x000055cb3be8eb90 rtorrent`___lldb_unnamed_symbol1612 + 64
    frame #18: 0x000055cb3bf2d52d rtorrent`___lldb_unnamed_symbol3094 + 749
    frame #19: 0x000055cb3bf4dcc6 rtorrent`___lldb_unnamed_symbol3461 + 118
    frame #20: 0x000055cb3bf4dcfd rtorrent`___lldb_unnamed_symbol3462 + 29
    frame #21: 0x000055cb3bf06261 rtorrent`___lldb_unnamed_symbol2775 + 65
    frame #22: 0x00007f7f50e94779 libtorrent.so.25`torrent::Poll::process() + 217
    frame #23: 0x00007f7f50e903f3 libtorrent.so.25`torrent::utils::Thread::event_loop() + 179
    frame #24: 0x000055cb3be88598 rtorrent`___lldb_unnamed_symbol1535 + 11880
    frame #25: 0x00007f7f508376b5 libc.so.6`__libc_start_call_main(main=(rtorrent`___lldb_unnamed_symbol1535), argc=1, argv=0x00007ffc4107c078) at libc_start_call_main.h:58:16
    frame #26: 0x00007f7f50837769 libc.so.6`__libc_start_main_impl(main=(rtorrent`___lldb_unnamed_symbol1535), argc=1, argv=0x00007ffc4107c078, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007ffc4107c068) at libc-start.c:360:3
    frame #27: 0x000055cb3be8a765 rtorrent`___lldb_unnamed_symbol1537 + 37
  thread #2, name = 'rtorrent disk', stop reason = signal SIGSTOP
    frame #0: 0x00007f7f508ade22 libc.so.6`__syscall_cancel_arch at syscall_cancel.S:56
    frame #1: 0x00007f7f508a1fda libc.so.6`__internal_syscall_cancel(a1=<unavailable>, a2=<unavailable>, a3=<unavailable>, a4=<unavailable>, a5=0, a6=0, nr=232) at cancellation.c:49:12
    frame #2: 0x00007f7f508a2024 libc.so.6`__syscall_cancel(a1=<unavailable>, a2=<unavailable>, a3=<unavailable>, a4=<unavailable>, a5=0, a6=0, nr=232) at cancellation.c:75:11
    frame #3: 0x00007f7f50929475 libc.so.6`epoll_wait(epfd=<unavailable>, events=<unavailable>, maxevents=<unavailable>, timeout=<unavailable>) at epoll_wait.c:30:10
    frame #4: 0x00007f7f50e93735 libtorrent.so.25`torrent::Poll::poll(int) + 53
    frame #5: 0x00007f7f50e99b97 libtorrent.so.25`torrent::Poll::do_poll(long) + 39
    frame #6: 0x00007f7f50e903f3 libtorrent.so.25`torrent::utils::Thread::event_loop() + 179
    frame #7: 0x00007f7f50e91086 libtorrent.so.25`torrent::utils::Thread::enter_event_loop(void*) + 38
    frame #8: 0x00007f7f508a57eb libc.so.6`start_thread(arg=<unavailable>) at pthread_create.c:448:8
    frame #9: 0x00007f7f5092918c libc.so.6`__clone3 at clone3.S:78
  thread #3, name = 'rtorrent net', stop reason = signal SIGSTOP
    frame #0: 0x00007f7f508ade22 libc.so.6`__syscall_cancel_arch at syscall_cancel.S:56
    frame #1: 0x00007f7f508a1fda libc.so.6`__internal_syscall_cancel(a1=<unavailable>, a2=<unavailable>, a3=<unavailable>, a4=<unavailable>, a5=0, a6=0, nr=232) at cancellation.c:49:12
    frame #2: 0x00007f7f508a2024 libc.so.6`__syscall_cancel(a1=<unavailable>, a2=<unavailable>, a3=<unavailable>, a4=<unavailable>, a5=0, a6=0, nr=232) at cancellation.c:75:11
    frame #3: 0x00007f7f50929475 libc.so.6`epoll_wait(epfd=<unavailable>, events=<unavailable>, maxevents=<unavailable>, timeout=<unavailable>) at epoll_wait.c:30:10
    frame #4: 0x00007f7f50e93735 libtorrent.so.25`torrent::Poll::poll(int) + 53
    frame #5: 0x00007f7f50e99b97 libtorrent.so.25`torrent::Poll::do_poll(long) + 39
    frame #6: 0x00007f7f50e903f3 libtorrent.so.25`torrent::utils::Thread::event_loop() + 179
    frame #7: 0x00007f7f50e91086 libtorrent.so.25`torrent::utils::Thread::enter_event_loop(void*) + 38
    frame #8: 0x00007f7f508a57eb libc.so.6`start_thread(arg=<unavailable>) at pthread_create.c:448:8
    frame #9: 0x00007f7f5092918c libc.so.6`__clone3 at clone3.S:78
  thread #4, name = 'rtorrent main', stop reason = signal SIGSTOP
    frame #0: 0x00007f7f508ade22 libc.so.6`__syscall_cancel_arch at syscall_cancel.S:56
    frame #1: 0x00007f7f508a1fda libc.so.6`__internal_syscall_cancel(a1=<unavailable>, a2=<unavailable>, a3=<unavailable>, a4=<unavailable>, a5=0, a6=0, nr=232) at cancellation.c:49:12
    frame #2: 0x00007f7f508a2024 libc.so.6`__syscall_cancel(a1=<unavailable>, a2=<unavailable>, a3=<unavailable>, a4=<unavailable>, a5=0, a6=0, nr=232) at cancellation.c:75:11
    frame #3: 0x00007f7f50929475 libc.so.6`epoll_wait(epfd=<unavailable>, events=<unavailable>, maxevents=<unavailable>, timeout=<unavailable>) at epoll_wait.c:30:10
    frame #4: 0x00007f7f50e93735 libtorrent.so.25`torrent::Poll::poll(int) + 53
    frame #5: 0x00007f7f50e99b97 libtorrent.so.25`torrent::Poll::do_poll(long) + 39
    frame #6: 0x00007f7f50e903f3 libtorrent.so.25`torrent::utils::Thread::event_loop() + 179
    frame #7: 0x00007f7f50e91086 libtorrent.so.25`torrent::utils::Thread::enter_event_loop(void*) + 38
    frame #8: 0x00007f7f508a57eb libc.so.6`start_thread(arg=<unavailable>) at pthread_create.c:448:8
    frame #9: 0x00007f7f5092918c libc.so.6`__clone3 at clone3.S:78
  thread #5, name = 'rtorrent scgi', stop reason = signal SIGSTOP
    frame #0: 0x00007f7f508ade22 libc.so.6`__syscall_cancel_arch at syscall_cancel.S:56
    frame #1: 0x00007f7f508a1fda libc.so.6`__internal_syscall_cancel(a1=<unavailable>, a2=<unavailable>, a3=<unavailable>, a4=<unavailable>, a5=0, a6=0, nr=232) at cancellation.c:49:12
    frame #2: 0x00007f7f508a2024 libc.so.6`__syscall_cancel(a1=<unavailable>, a2=<unavailable>, a3=<unavailable>, a4=<unavailable>, a5=0, a6=0, nr=232) at cancellation.c:75:11
    frame #3: 0x00007f7f50929475 libc.so.6`epoll_wait(epfd=<unavailable>, events=<unavailable>, maxevents=<unavailable>, timeout=<unavailable>) at epoll_wait.c:30:10
    frame #4: 0x00007f7f50e93735 libtorrent.so.25`torrent::Poll::poll(int) + 53
    frame #5: 0x00007f7f50e99b97 libtorrent.so.25`torrent::Poll::do_poll(long) + 39
    frame #6: 0x00007f7f50e903f3 libtorrent.so.25`torrent::utils::Thread::event_loop() + 179
    frame #7: 0x00007f7f50e91086 libtorrent.so.25`torrent::utils::Thread::enter_event_loop(void*) + 38
    frame #8: 0x00007f7f508a57eb libc.so.6`start_thread(arg=<unavailable>) at pthread_create.c:448:8
    frame #9: 0x00007f7f5092918c libc.so.6`__clone3 at clone3.S:78
(lldb) q
Quitting LLDB will detach from one or more processes. Do you really want to proceed: [Y/n] 

```

**Comment by rakshasa** [comment]
Ok, so what likely happens here is that previously we had a global lock that the main thread temporarily released during execution of external commands.

This meant that SCGI requests worked (different thread handles it), so UI requests, etc, were being processed.

However the main thread remains frozen. And now that threading has been improved (and made safer), all UI requests routed through the main thread. (SCGI handling is still done in a separate thread, just the commands it calls are handled in the main thread)

Thus any external commands, such as those you posted, always froze the main thread but now you have the UI also freezing.

The solution is to run those commands in the background.

**Comment by rakshasa** [comment]
So why does rtcontrol get stuck?

Don't know what rtcontrol does, so hard to say.

Anyway, try `execute.nothrow.bg` and see if the rtcontrol processes finish. Note that you don't get exit status codes when running in background.

**Comment by rakshasa** [comment]
Although I'm curious as to why there's two `rtorrent main` threads, this seems wrong.

**Comment by rakshasa** [comment]
You don't have an `rtorrent tracker` thread, as you sure you've compiled the latest master of both rtorrent and libtorrent?

**Comment by laplacesdaemon** [comment]
The commands work with execute.nothrow.bg

And yes, it is master of both libtorrent and rtorrent.

**Comment by rakshasa** [comment]
Thread #4 should have been `rtorrent tracker`, the pthread name was was fixed a month or so ago.

So the backtrace is not from master.

**Comment by laplacesdaemon** [comment]
I'm on Arch Linux. To build I modified the PKGBUILDs for both libtorrent and rtorrent. Unless I'm missing something this is from master.

```
pkgname=rtorrent
pkgver=0.15.4
pkgrel=1
pkgdesc='Ncurses BitTorrent client based on libTorrent'
url='https://rakshasa.github.io/rtorrent/'
license=('GPL-2.0-or-later')
arch=('x86_64')
makedepends=('git')
depends=("libtorrent=${pkgver}" 'curl' 'tinyxml2')
source=("git+https://github.com/rakshasa/rtorrent.git#commit=231606afc16eef08ec1a344a7aaef7504343bb71")
sha256sums=('SKIP')

prepare() {
  cd ${pkgname}
  autoreconf -fiv
}

build() {
  cd ${pkgname}
  ./configure \
  --prefix=/usr \
  --enable-debug \
  --with-xmlrpc-tinyxml2
  make
}

package() {
  cd ${pkgname}
  make DESTDIR="${pkgdir}" install
  install -D doc/rtorrent.rc "${pkgdir}"/usr/share/doc/rtorrent/rtorrent.rc
}

```

```
pkgname=libtorrent
pkgver=0.15.4
pkgrel=1
pkgdesc='BitTorrent library with a focus on high performance'
url='https://rakshasa.github.io/rtorrent/'
arch=('x86_64')
license=('GPL-2.0-or-later')
makedepends=('git')
depends=('openssl')
source=("git+https://github.com/rakshasa/libtorrent.git#commit=a0a364e2863356f51d41a27ce7620471666c5c56")
sha256sums=('SKIP')

prepare() {
  cd ${pkgname}
  autoreconf -fiv
}

build() {
  cd ${pkgname}
  ./configure \
  --prefix=/usr \
  --enable-debug
  make
}

package() {
  cd ${pkgname}
  make DESTDIR="${pkgdir}" install
}

```

**Comment by rakshasa** [comment]
Most likely you have old rtorrent binaries/libraries somewhere in your PATH.

**Comment by laplacesdaemon** [comment]
I just checked and there is only one (this last build) copy of rtorrent and libtorrent installed in the whole system.

**Comment by rakshasa** [comment]
The backtrace shows a pthread name for the tracker thread that is from before I fixed it a few weeks ago, so it isn't master.

So almost guaranteed the issue is on your end.

**Comment by laplacesdaemon** [comment]
I've just installed the official Arch packages for 0.15.4.  I've made sure there is only that rtorrent (this is a dedicated machine to rtorrent). Running lldb also shows two threads named "rtorrent main".

Anyway, thank for the support on the issue.
