### ISSUE TITLE
rtorrent 0.9.6 crashing

### ISSUE THREAD

**Issue by hilalafridi** [rakshasa/rtorrent#328]
getting the following
 Caught internal_error: Read past initial payload after incoming encrypted handshake.39.129] [Bind xxx.xxx.xxx.xxx]                        [U 1655/20490] [D 2562/20490] [H 0/2048] [S 574/14006/65023] [F 8192/8192]
/opt/lib/libtorrent.so.19(_ZN7torrent14internal_error10initializeERKSs+0x202) [0x7f039f1b7672]
/opt/bin/rtorrent(_ZN7torrent14internal_errorC2EPKc+0x3e) [0x445f9e]
/opt/lib/libtorrent.so.19(+0xc2e14) [0x7f039f247e14]
/opt/lib/libtorrent.so.19(_ZN7torrent9PollEPoll7performEv+0xd7) [0x7f039f1c8a37]
/opt/lib/libtorrent.so.19(_ZN7torrent9PollEPoll7do_pollEli+0x50) [0x7f039f1c8ae0]
/opt/lib/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x11c) [0x7f039f2027ac]
/opt/bin/rtorrent() [0x41216d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f039dd7bec5]
/opt/bin/rtorrent() [0x4128b4]

**Comment by hilalafridi** [comment]
Caught internal_error: HashTorrent::confirm_checked() m_outstanding != 0.
/opt/lib/libtorrent.so.19(_ZN7torrent14internal_error10initializeERKSs+0x202) [0x7f258b99a672]
/opt/bin/p2pedia-delivery-agentrtorrent(_ZN7torrent14internal_errorC2EPKc+0x3e) [0x445f9e]
/opt/lib/libtorrent.so.19(+0x873fb) [0x7f258b9ef3fb]
/opt/lib/libtorrent.so.19(+0xb1c6b) [0x7f258ba19c6b]
/opt/lib/libtorrent.so.19(+0x2ecda) [0x7f258b996cda]
/opt/lib/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x18a) [0x7f258b9e581a]
/opt/bin/p2pedia-delivery-agentrtorrent() [0x41216d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f258a55eec5]
/opt/bin/p2pedia-delivery-agentrtorrent() [0x4128b4]

**Comment by hilalafridi** [comment]
Caught internal_error: HashTorrent::confirm_checked() m_outstanding != 0.
/opt/lib/libtorrent.so.19(_ZN7torrent14internal_error10initializeERKSs+0x202) [0x7f258b99a672]
/opt/bin/p2pedia-delivery-agentrtorrent(_ZN7torrent14internal_errorC2EPKc+0x3e) [0x445f9e]
/opt/lib/libtorrent.so.19(+0x873fb) [0x7f258b9ef3fb]
/opt/lib/libtorrent.so.19(+0xb1c6b) [0x7f258ba19c6b]
/opt/lib/libtorrent.so.19(+0x2ecda) [0x7f258b996cda]
/opt/lib/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x18a) [0x7f258b9e581a]
/opt/bin/rtorrent() [0x41216d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f258a55eec5]
/opt/bin/rtorrent() [0x4128b4]

**Comment by blardyblar** [comment]
Yeah, I'm getting the same thing every 3 hours, this needs to be fixed quickly. I'd say it's a pretty severe bug that rtorrent doesn't run more than 3 hours at a time right now

**Comment by hilalafridi** [comment]
Getting the following now.
1448423301 C Caught signal: 'Segmentation fault.
---DUMP---
Caught Segmentation fault, dumping stack:
/opt/bin/rtorrent() [0x412dc0]
/opt/bin/rtorrent() [0x4492e6]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f26eb285340]
/opt/lib/libtorrent.so.19(+0x9d2eb) [0x7f26ec3782eb]
/opt/lib/libtorrent.so.19(+0x9b6e3) [0x7f26ec3766e3]
/opt/lib/libtorrent.so.19(+0x9920a) [0x7f26ec37420a]
/opt/lib/libtorrent.so.19(+0x9970b) [0x7f26ec37470b]
/opt/lib/libtorrent.so.19(+0x9a02d) [0x7f26ec37502d]
/opt/lib/libtorrent.so.19(+0x9a206) [0x7f26ec375206]
/opt/lib/libtorrent.so.19(+0x9abb1) [0x7f26ec375bb1]
/opt/lib/libtorrent.so.19(_ZN7torrent9PollEPoll7performEv+0xd7) [0x7f26ec31ea37]
/opt/lib/libtorrent.so.19(_ZN7torrent9PollEPoll7do_pollEli+0x50) [0x7f26ec31eae0]
/opt/lib/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x11c) [0x7f26ec3587ac]
/opt/bin/rtorrent() [0x41216d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f26eaed1ec5]
/opt/bin/rtorrent() [0x4128b4]

**Comment by VJean-dev** [comment]
rTorrent: [0.9.6](https://github.com/rakshasa/rtorrent/releases/tag/0.9.6) cf1ba60 on 3 Sep 2015
libTorrent: [0.13.6](https://github.com/rakshasa/libtorrent/releases/tag/0.13.6) a67d9c8 on 3 Sep 2015

```
1471898560 I handshake_manager->_ip_: Adding incoming connection: fd:526.
1471898560 I handshake_manager->_ip_: Adding incoming connection: fd:527.
1471898560 I handshake_manager->_ip_: Adding incoming connection: fd:528.
1471898560 I _torrent_hash_->tracker_list: Failed to connect to tracker url:'dht://' msg:'DHT search unsuccessful.'.
1471898560 C Caught signal: 'Segmentation fault.
---DUMP---
Caught Segmentation fault, dumping stack:
rtorrent() [0x414c8c]
rtorrent() [0x451aa7]
/lib/x86_64-linux-gnu/libc.so.6(+0x321a0) [0x7f7bf0b5b1a0]
/usr/local/lib/libtorrent.so.19(+0x9da75) [0x7f7bf235aa75]
/usr/local/lib/libtorrent.so.19(+0x994fb) [0x7f7bf23564fb]
/usr/local/lib/libtorrent.so.19(+0x99de5) [0x7f7bf2356de5]
/usr/local/lib/libtorrent.so.19(+0x9a0ae) [0x7f7bf23570ae]
/usr/local/lib/libtorrent.so.19(+0x9a69c) [0x7f7bf235769c]
/usr/local/lib/libtorrent.so.19(_ZN7torrent9PollEPoll7performEv+0xdb) [0x7f7bf2306f5b]
/usr/local/lib/libtorrent.so.19(_ZN7torrent9PollEPoll7do_pollEli+0x62) [0x7f7bf2307002]
/usr/local/lib/libtorrent.so.19(_ZN7torrent11thread_base10event_loopEPS0_+0x11c) [0x7f7bf233bd4c]
rtorrent() [0x4140a7]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd) [0x7f7bf0b47ead]
rtorrent() [0x4147a5]

---END---
```

Crutch fixed with setting: `dht.mode.set = disable`. Before it was `dht.mode.set = on`
Over 1,2k torrents. 
I know it's very old code, wait stable releases.

**Comment by mikerev** [comment]
This still exists on Ubuntu 16.04 rtorrent 0.9.6-2build1

Building from source fails with some dht related error too. Hopefully @vjean-dev's solution does it for me too - sad to see rtorrent dead and so unstable.

**Comment by rakshasa** [comment]
Closing this and if you continue having issues create a new issue where this happens on current git head.
