### ISSUE TITLE
Magnet/DHT torrents refuse to work in rtorrent for me

### ISSUE THREAD

**Issue by haasn** [rakshasa/rtorrent#602]
Reproduction steps:
1. Start rtorrent
2. Add magnet link of torrent that I know is popular. (I won't link any, but I'm sure you can find plenty on your own)
3. Wait an hour
4. Nothing happens, it's still only listed as the hash. The `dht://` tracker is listed as `0f / 1s (0) on S/L/D: 0/0/0 (0/1` or something like that.

I have confirmed that:
1. This is not a ports issue. I *am* connectable, both the DHT port and the rtorrent main port. Yes, I tested both TCP and UDP. I can `tcpdump port <dht port>` and see lots of UDP DHT traffic going both ways.
2. This is not an issue with the torrent. I can add it to transmission or deluge and it starts downloading within a second in both, even before I open their ports! Only rtorrent fails.
3. It fails working even if I extract the .torrent from one of the aforemention clients and add it directly to rtorrent (that is, with no additional trackers besides `dht://`).

Versions:
- libtorrent 0.13.6
- rtorrent 0.9.6
- I am not using custom patches. I am not using libressl.

Configuration:
```
port_range = XXXXX-XXXXX
port_random = no
download_rate = 9000
upload_rate = 500

directory = ~/torrents
session = ~/.rtsession

use_udp_trackers = yes
encryption = allow_incoming, try_outgoing
dht = on
dht_port = YYYYY
peer_exchange = yes
```

Is there anything I can do, except “switch to deluge or transmission?”. Regular torrents work fine for me in rtorrent and I would not like to switch clients just for magnet links, if I can avoid it.

**Comment by chros73** [comment]
Maybe because of [this](https://github.com/rakshasa/rtorrent/issues/61)? Try it out without encryption.

**Comment by haasn** [comment]
@chros73 Must be a different bug, because #61 indicates the issue going away when using `encryption = allow_incoming, try_outgoing`.

**Comment by chros73** [comment]
I saw that but give it a try with the mentioned config entry anyway, it worked for me.

**Comment by soredake** [comment]
Same for me, but i'm on rtorrent/libtorrent-ps and libressl, this https://github.com/rakshasa/rtorrent/issues/602#issuecomment-300064177 helps me for now.

**Comment by getmeacuboftea** [comment]
I have the same problems, and it definitely not the problems with encryptions.
When i try 2 different magnet links: [lubuntu](magnet:?xt=urn:btih:fb79819145731bd20a4570f73f335b534a99e0d2&dn=lubuntu-17.04-desktop-amd64.iso) and [arch](magnet:?xt=urn:btih:83c79a07deb50a58e90628ef1475748657e784c5&dn=archlinux-2017.06.01-x86_64.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce) the arch magnet link work perpectly because it have upd/http tracker, on the other hand the lubuntu link stand there forever, the same problem happens with any torrent **only** use dht.

**Comment by chros73** [comment]
Can you link/copy the magnet URI of lubuntu?

**Comment by getmeacuboftea** [comment]
Yes, it here magnet:?xt=urn:btih:fb79819145731bd20a4570f73f335b534a99e0d2&dn=lubuntu-17.04-desktop-amd64.iso
I was use it as reference link but it didn't show up, sorry.

**Comment by chros73** [comment]
It works for me with current git version (rtorrent-ps-ch 1.5.0-0.9.7) and [this config](https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent-config.rc#L153).
The Magnet links for lubuntu are on [this page](http://lubuntu.me/downloads/).
I used this one:
`magnet:?xt=urn:btih:fb79819145731bd20a4570f73f335b534a99e0d2&dn=lubuntu-17.04-desktop-amd64.iso`

**Comment by getmeacuboftea** [comment]
Thanks, i've try some other version or config but it's still the same problems. It's the "DHT search unsuccessful" describle in here https://github.com/rakshasa/rtorrent/wiki/Using-DHT.
It seems like rtorrent need some port forward for the dht feature to work.

**Comment by chros73** [comment]
> Seems like rtorrent need some port forward for the dht feature to work.

It can be, just open [dht_port](https://github.com/chros73/rtorrent-ps_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent-config.rc#L177) as well.

**Comment by getmeacuboftea** [comment]
Sorry to bring this up again, but after a while a realize that the number of peer in dht have no meaning, it always show 0/0/0 even when everything is working fine.
And i can enable force encrypt in rtorrent with the help of aria2, it can convert magnet link to real torrent file so there's no need for a fake torrent file anymore. :).

**Comment by chros73** [comment]
> And i can enable force encrypt in rtorrent with the help of aria2, it can convert magnet link to real torrent file so there's no need for a fake torrent file anymore. :).

Pretty good idea, thanks!

**Comment by necb77** [comment]
I am experiencing similar behavior using rtorrent version 0.9.6 on Ubuntu 16.04.3.  I used the lubuntu magnet link chros37 posted.  This one...

`magnet:?xt=urn:btih:fb79819145731bd20a4570f73f335b534a99e0d2&dn=lubuntu-17.04-desktop-amd64.iso`

DHT works and says something like 14/20 nodes replied.  Then the torrent just sits there and never downloads.  My config has the following....

```
dht.mode.set = on
dht_port = 6881

schedule2 = dht_node_1, 5, 0, "dht.add_node=router.utorrent.com:6881"
schedule2 = dht_node_2, 5, 0, "dht.add_node=dht.transmissionbt.com:6881"
schedule2 = dht_node_3, 5, 0, "dht.add_node=router.bitcomet.com:6881"
schedule2 = dht_node_4, 5, 0, "dht.add_node=dht.aelitis.com:6881"

protocol.pex.set = yes 
trackers.use_udp.set = 1
encryption = allow_incoming,enable_retry,prefer_plaintext
```

Was anyone able to resolve this?

**Comment by necb77** [comment]
One more thing.  I have a VPN that I connect through.  This fix works fine when I'm not using my VPN, however, when I do use my VPN I'm back to the same problem because my VPN does not allow port forwarding.  Is it safe to say I cannot use rtorrent through my VPN?

**Comment by getmeacuboftea** [comment]
@necb77  
Yes, rtorrent need open port for dht to work. It would be nice if someone can make a patch so you can turn on/off that requirement on demand.

**Comment by necb77** [comment]
@getmeacuboftea 
Dang, sorry to hear that.  It looks like rtorrent is not suitable for me.

**Comment by chros73** [comment]
Or choose a provider that supports port forwarding.

**Comment by Ramzec** [comment]
Hi. I have the similar issue (gentoo, rtorrent version 0.9.6):

```
# rtorrent -d /data/torrents -s ~/.config/rtorrent/session -o dht=on,dht_port=6881,dht.add_node=dht.transmissionbt.com
rtorrent: Failed to parse command line option: DHT not enabled.
```

I tried to define the same params via ~/.rtorrent.rc, but result the same: DHT not enabled

Without ```dht.add_node=dht.transmissionbt.com``` it starts successfully, but nothing happens.

**Comment by chros73** [comment]
Take a look at [this](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#supporting-public-torrents-magnet-links-udp-trackers-dht), maybe it helps.

**Comment by CarlosMC** [comment]
Hi there, 
I was having the same problem, when using  xmlrpc on python.
Adding maglinks with label or with the download directory results in paused torrents that never start. 

server = xmlrpclib.Server(server_url)
result = server.load_start_verbose(maglink,
						"d.set_directory="+"\""+downloadDir+"\"",
						"d.set_custom1="+"\""+label+"\"")

If i just submit the link without any other parameter it begins to work.
result = server.load_start_verbose(maglink).

**Comment by tserversbfs** [comment]
> Sorry to bring this up again, but after a while i saw that the number of peer in dht have no meaning, it always show 0/0/0 even when everything is working fine.
> And i can enable force encrypt in rtorrent with the help of aria2, it can convert magnet link to real torrent file so there's no need for a fake torrent file anymore. :).
> Also (in my case), i can confirm that you don't need to open dht_port, just open the torrent port is enough for dht, netstat didn't show the dht port as listening so i think it's obvious.

Please, could you explain what and how you did this?

**Comment by chros73** [comment]
> could you explain what and how you did this?

Something similar [like this](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/bin/addMagnetLinksAria2.sh).

**Comment by Martyn575** [comment]
This has suddenly started happening to me today. I've got no idea why. It was working before but now it reporting all magnets as suddenly not working.

**Comment by rakshasa** [comment]
Fixed.

**Comment by billbeans** [comment]
> Fixed.

Hello, I've compiled the latest version of rtorrent/librtorrent from source and I still can't start magnet links. I have a VPN that does not allow port forwarding, but according to the wiki, I should still be able to start them. They work in other clients such as qbittorrent.

ref: https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#supporting-public-torrents-magnet-links-udp-trackers-dht

> • TCP/UDP port for tracker communication: DHT requires open/forwarded port(s) to work with this/these port(s)!
> • UDP port for DHT (DHT **does not** require open/forwarded port to work with this port)

**Comment by rakshasa** [comment]
Make sure you are using 0.16.2 and check the `dht_all` and `tracker_requests` logs.

**Comment by billbeans** [comment]
I compiled 0.16.2 and now the program is terminating after about a minute with this message:
```
terminate called after throwing an instance of 'torrent::internal_error'                           
                                                                          what():  Poll::modify(...) epoll_ctl(9, 3 -> 3, 686, [0x7f599c6f1ab0:8]) = 9: Bad file descriptor
                    Aborted
```
I'm not sure if I did something wrong with the manual install or if this is a new bug. I installed libtorrent to `~/.local` of which `lib` is in my `LD_LIBRARY_PATH` and the actual `rtorrent` binary resides in my home bin.

**Comment by rakshasa** [comment]
Try latest master branch.

**Comment by Sappurit** [comment]
My 0.16.1 works well. But 0.16.2 to 0.16.5 error within 1-2 min.
I think it happens with http(s) tracker. 
Work well with UDP tracker(s) from magnet and .torrent

```
terminate called after throwing an instance of 'torrent::internal_error' 
what():  Poll::modify(...) epoll_ctl(9, 3 -> 3, 24, [0x7f5af0008f80:8]) = 9: Bad file descriptor
Aborted (core dumped)
```

**Comment by rakshasa** [comment]
Try `master`, create a new ticket with `connection` logs.

Also try attaching to rtorrent with `lldb -p <pid>`, `breakpoint set -r torrent::internal_error::initialize` to get a backtrace.
